services:
  api:
    container_name: hearlers-nest-api-dev
    restart: always
    build: .
    working_dir: /usr/src/app
    command: ["yarn", "start:dev"]
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "50051:50051"
