export enum ContextDomain {
  EMOTION = "EMOTION",
  RISK = "RISK",
  MOTIVATION = "MOTIVATION",
  SUPPORT_SLEEP_COGNITIVE = "SUPPORT_SLEEP_COGNITIVE",
  ALLIANCE = "ALLIANCE",
  IMPACT_TIMEFRAME = "IMPACT_TIMEFRAME",
}
