export enum CounselPromptType {
  UNSPECIFIED = 0,
  SYSTEM_MSG = 1,
  POSITIVE_MSG = 2,
  DEPRESSED_REASON_MSG = 3,
  DEPRESSED_NO_REASON_MSG = 4,
  ANXIOUS_REASON_MSG = 5,
  ANXIOUS_NO_REASON_MSG = 6,
  TIRED_REASON_MSG = 7,
  TIRED_NO_REASON_MSG = 8,
  WHY_LIVE_MSG = 9,
  BRANCH_MSG = 10,
}
